name: Build and Upload Python Package to GitHub release and PyPi

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build & Upload to GitHub / PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/smoothiepy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PDM and plugin
        run: |
          python -m pip install --upgrade pip
          pip install pdm[pdm-publish]
          pdm install

      - name: Build project
        run: pdm build

      - name: Upload artifacts to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz

      - name: Publish to PyPI
        run: pdm publish --no-build --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
