name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  publish:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/smoothiepy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PDM and plugin
        run: |
          python -m pip install --upgrade pip
          pip install pdm[pdm-publish]
          pdm install

      - name: Build package with PDM
        run: pdm build

      - name: Publish to PyPI
        run: pdm publish --no-build --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
